/**
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DslIdeModule extends AbstractDslIdeModule {
}
