/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.parser.antlr;

import com.google.inject.Inject;
import com.senacor.bdm.techdsl.parser.antlr.internal.InternalTechDslParser;
import com.senacor.bdm.techdsl.services.TechDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class TechDslParser extends AbstractAntlrParser {

	@Inject
	private TechDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTechDslParser createParser(XtextTokenStream stream) {
		return new InternalTechDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LogDocument";
	}

	public TechDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TechDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
