/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.logdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLogDslScopeProvider extends DelegatingScopeProvider {
}
