/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.logdsl.ui.tests;

import com.google.inject.Injector;
import com.senacor.bdm.logdsl.ui.internal.LogdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LogDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LogdslActivator.getInstance().getInjector("com.senacor.bdm.logdsl.LogDsl");
	}

}
