/**
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.tests;

import com.google.inject.Inject;
import com.senacor.bdm.model.logmetamodel.LogDocument;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(TechDslInjectorProvider.class)
@SuppressWarnings("all")
public class TechDslParsingTest {
  @Inject
  private ParseHelper<LogDocument> parseHelper;
}
