/**
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.formatting2;

import com.google.inject.Inject;
import com.senacor.bdm.model.metamodel.LogDocument;
import com.senacor.bdm.services.DslGrammarAccess;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class DslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DslGrammarAccess _dslGrammarAccess;
  
  protected void _format(final LogDocument doc, final IFormattableDocument document) {
  }
  
  public void format(final Object doc, final IFormattableDocument document) {
    if (doc instanceof XtextResource) {
      _format((XtextResource)doc, document);
      return;
    } else if (doc instanceof LogDocument) {
      _format((LogDocument)doc, document);
      return;
    } else if (doc instanceof EObject) {
      _format((EObject)doc, document);
      return;
    } else if (doc == null) {
      _format((Void)null, document);
      return;
    } else if (doc != null) {
      _format(doc, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(doc, document).toString());
    }
  }
}
