/**
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.formatting2;

import com.google.inject.Inject;
import com.senacor.bdm.model.metamodel.BaseEntity;
import com.senacor.bdm.model.metamodel.Document;
import com.senacor.bdm.services.DslGrammarAccess;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public abstract class DslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private DslGrammarAccess _dslGrammarAccess;
  
  protected void _format(final Document document) {
    EList<BaseEntity> _baseentities = document.getBaseentities();
    for (final BaseEntity baseEntity : _baseentities) {
      this.format(document);
    }
  }
  
  public void format(final Document document) {
    _format(document);
    return;
  }
}
