<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metamodel" nsURI="http://www.example.org/metamodel" nsPrefix="metamodel">
  <eClassifiers xsi:type="ecore:EClass" name="LogDocument" eSuperTypes="#//Document">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Member" containment="true" eOpposite="#//Member/logdocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Member" abstract="true" eSuperTypes="#//INamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="logdocument" eType="#//LogDocument"
        eOpposite="#//LogDocument/members"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fielddeclarations" upperBound="-1"
        eType="#//FieldDeclaration" containment="true" eOpposite="#//FieldDeclaration/member"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Document" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TechDocument" eSuperTypes="#//Document"/>
  <eClassifiers xsi:type="ecore:EClass" name="MappingDocument" eSuperTypes="#//Document"/>
  <eClassifiers xsi:type="ecore:EClass" name="INamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entitysatelite" upperBound="-1"
        eType="#//ExtensionSatelite" containment="true" eOpposite="#//ExtensionSatelite/entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainsatelit" eType="#//BaseEntity"
        containment="true" eOpposite="#//BaseEntity/entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="businesskeys" upperBound="-1"
        eType="#//BusinessKey" containment="true" eOpposite="#//BusinessKey/entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExtensionSatelite" eSuperTypes="#//INamedElement #//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        eOpposite="#//Entity/entitysatelite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseEntity" eSuperTypes="#//INamedElement #//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        eOpposite="#//Entity/mainsatelit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field" eSuperTypes="#//INamedElement #//FieldDeclaration"/>
  <eClassifiers xsi:type="ecore:EClass" name="BusinessKey">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fielddeclaration" upperBound="-1"
        eType="#//FieldDeclaration"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//Entity"
        eOpposite="#//Entity/businesskeys"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldDeclaration" abstract="true" interface="true"
      eSuperTypes="#//Member">
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" eType="#//Member"
        eOpposite="#//Member/fielddeclarations"/>
  </eClassifiers>
</ecore:EPackage>
