/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTechDslScopeProvider extends DelegatingScopeProvider {
}
