/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.senacor.bdm.DslRuntimeModule;
import com.senacor.bdm.DslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DslIdeSetup extends DslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DslRuntimeModule(), new DslIdeModule()));
	}
	
}
