/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.ide

import com.google.inject.Guice
import com.senacor.bdm.DslRuntimeModule
import com.senacor.bdm.DslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class DslIdeSetup extends DslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new DslRuntimeModule, new DslIdeModule))
	}
	
}
