/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.serializer;

import com.google.inject.Inject;
import com.senacor.bdm.model.metamodel.BaseEntity;
import com.senacor.bdm.model.metamodel.ExtensionSatelite;
import com.senacor.bdm.model.metamodel.Field;
import com.senacor.bdm.model.metamodel.LogDocument;
import com.senacor.bdm.model.metamodel.MetamodelPackage;
import com.senacor.bdm.services.DslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class DslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private DslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MetamodelPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MetamodelPackage.BASE_ENTITY:
				sequence_BaseEntity(context, (BaseEntity) semanticObject); 
				return; 
			case MetamodelPackage.EXTENSION_SATELITE:
				sequence_ExtensionSatelite(context, (ExtensionSatelite) semanticObject); 
				return; 
			case MetamodelPackage.FIELD:
				sequence_Field(context, (Field) semanticObject); 
				return; 
			case MetamodelPackage.LOG_DOCUMENT:
				sequence_LogDocument(context, (LogDocument) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Member returns BaseEntity
	 *     BaseEntity returns BaseEntity
	 *
	 * Constraint:
	 *     (name=ID fielddeclarations+=FieldDeclaration)
	 */
	protected void sequence_BaseEntity(ISerializationContext context, BaseEntity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns ExtensionSatelite
	 *     ExtensionSatelite returns ExtensionSatelite
	 *
	 * Constraint:
	 *     (name=ID fielddeclarations+=FieldDeclaration)
	 */
	protected void sequence_ExtensionSatelite(ISerializationContext context, ExtensionSatelite semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Member returns Field
	 *     FieldDeclaration returns Field
	 *     Field returns Field
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Field(ISerializationContext context, Field semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MetamodelPackage.Literals.INAMED_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MetamodelPackage.Literals.INAMED_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFieldAccess().getNameIDTerminalRuleCall_2_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     LogDocument returns LogDocument
	 *
	 * Constraint:
	 *     (name=QualifiedName members+=Member)
	 */
	protected void sequence_LogDocument(ISerializationContext context, LogDocument semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
