/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import com.senacor.bdm.techdsl.TechDslRuntimeModule;
import com.senacor.bdm.techdsl.TechDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class TechDslIdeSetup extends TechDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new TechDslRuntimeModule(), new TechDslIdeModule()));
	}
	
}
