/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDslScopeProvider extends DelegatingScopeProvider {
}
