/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.logdsl.ui;

import com.google.inject.Injector;
import com.senacor.bdm.logdsl.ui.internal.LogdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(LogdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		LogdslActivator activator = LogdslActivator.getInstance();
		return activator != null ? activator.getInjector(LogdslActivator.COM_SENACOR_BDM_LOGDSL_LOGDSL) : null;
	}

}
