/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.validation

import com.senacor.bdm.validation.biz.MemberValidator
import org.eclipse.xtext.validation.ComposedChecks

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@ComposedChecks(validators=#[
	MemberValidator
])
class DslValidator extends AbstractDslValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					DslPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
