/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TechDslUiModule extends AbstractTechDslUiModule {

	public TechDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
