/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.logdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class LogDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/senacor/bdm/logdsl/parser/antlr/internal/InternalLogDsl.tokens");
	}
}
