/**
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class DslUiModule extends AbstractDslUiModule {
  public DslUiModule(final AbstractUIPlugin arg0) {
    super(arg0);
  }
}
