/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(DslInjectorProvider)
class DslParsingTest {

}
