/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.ui.tests;

import com.google.inject.Injector;
import com.senacor.bdm.ui.internal.BdmActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class DslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BdmActivator.getInstance().getInjector("com.senacor.bdm.Dsl");
	}

}
