/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.ui.tests;

import com.google.inject.Injector;
import com.senacor.bdm.techdsl.ui.internal.TechdslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class TechDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return TechdslActivator.getInstance().getInjector("com.senacor.bdm.techdsl.TechDsl");
	}

}
