/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl.ui;

import com.google.inject.Injector;
import com.senacor.bdm.techdsl.ui.internal.TechdslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TechDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(TechdslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		TechdslActivator activator = TechdslActivator.getInstance();
		return activator != null ? activator.getInjector(TechdslActivator.COM_SENACOR_BDM_TECHDSL_TECHDSL) : null;
	}

}
