/*
 * generated by Xtext 2.25.0
 */
package com.senacor.bdm.techdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TechDslStandaloneSetup extends TechDslStandaloneSetupGenerated {

	public static void doSetup() {
		new TechDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
